### PR TITLE
feat: upgrade axios

### PR DESCRIPTION
**Pull request by osslgtm**
upgrade axios

### CODE REVIEW

**Comment by osslgtm** [comment]
(updated commit message)

**Comment by rongquan1** [comment]
@osslgtm 

Could you try to test these changes by importing them into a new application and verify that the functions calling `axios` are working correctly? In particular, the `queryDns` function.

For more context, the creator website is not working with these changes.

**Comment by osslgtm** [comment]
@rongquan1 
https://github.com/osslgtm/test-dnsprove/

(added in protocol check in case https:// or http:// is used on dnsquery)

is there something specific that broke ?

**Comment by rongquan1** [comment]
@osslgtm 

Could you please take a look at the `document-creator-website` repo and try to import these changes?

We are encountering the following error: `TypeError: (0 , _axios.default) is not a function`.

**Comment by osslgtm** [comment]
is it on the editor side or during the build process ?

seems to work when importing it locally

```
"dependencies": {
  "@tradetrust-tt/dnsprove": "file:../dnsprove",
  "axios": "^1.7.2",
}
```

build and lint works as well

**Comment by rongquan1** [comment]
@osslgtm 

This is happening at runtime when we try to click a button on the UI which is supposed to call the function that triggers the axios.

**Comment by osslgtm** [comment]
Fixed, can try again

**Review by rongquan1 — APPROVED** [review]
Thanks! Can you update the `tt-verify` repo after this package is published?

**Comment by osslgtm** [comment]
sure!

**Comment by osslgtm** [comment]
the release seems to be failing, seems to be an npm token issue

**Comment by rongquan1** [comment]
@osslgtm package just released

**Comment by rongquan1** [comment]
@osslgtm 

Using relative path `import axios from "../node_modules/axios/index";` might cause some issues if it is not there. Will be reverting this changes.

**Comment by osslgtm** [comment]
@rongquan1 

Do you have details on the issue happening ? 

Would you prefer if we patch the issue or use an alternate package ?

Any info would be appreciated

**Comment by rongquan1** [comment]
@osslgtm 

We are open to using an alternative package to replace `axios` if it cannot be upgraded.

However, we must ensure that the replacement maintains all existing functionality.

**Pull request merged**
