### PR TITLE
feat(hedera): added support for hedera network by krypc team

### PR DESCRIPTION
**Pull request by piruthivi3232**

### CODE REVIEW

**Comment by superical** [comment]
Pls fix the issues.

**Comment by piruthivi3232** [comment]
> Pls fix the issues.

Fixed

**Comment by superical** [comment]
Still fail.

**Comment by piruthivi3232** [comment]
> Still fail.

subject added

**Comment by piruthivi3232** [comment]
plz close this as soon as possible

**Comment by superical** [comment]
> plz close this as soon as possible

You still have linter issues. Pls fix all your issues in one shot if you would like to close this sooner. It’s going to take multiple rounds like now if you are only fixing some but not the rest of the issues.

**Comment by piruthivi3232** [comment]
I have changed the commit msg, guide me if i am wrong

**Comment by superical** [comment]
Your PR is still failing. Pls fix the issues.

**Comment by piruthivi3232** [comment]
commit message changed

**Comment by piruthivi3232** [comment]
i have corrected commit msg.

**Comment by superical** [comment]
Please correct all commit msg.

**Comment by piruthivi3232** [comment]
I revised my commit message in accordance with the guidelines provided at https://commitlint.io/

**Comment by piruthivi3232** [comment]
checklist passed please merge.

**Review by superical — APPROVED** [review]

**Comment by piruthivi3232** [comment]
when it will merge?

**Comment by superical** [comment]
This PR was already approved a few weeks ago. You can merge whenever you're ready.

**Pull request merged**
